namespace AutoStartConfirm.AutoStarts {
    public enum Category {
        BootExecute,
        AppInit32,
        AppInit64,
        AppCertDll,
        Winlogon,
        UserInitMprLogonScript,
        GroupPolicyExtensions,
        DomainGroupPolicyScript,
        LocalGroupPolicyScript,
        GroupPolicyShellOverwrite,
        AlternateShell,
        AvailableShells,
        TerminalServerStartupPrograms,
        TerminalServerRun,
        TerminalServerInitialProgram,
        Run32,
        Run64,
        GroupPolicyRun,
        ActiveSetup32,
        ActiveSetup64,
        IconServiceLib,
        WindowsCEServices32,
        WindowsCEServices64,
    }
}
