# This is a workaround for skipped main ci runs
# See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

name: Build & Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'AutoStartConfirm/**'
      - 'AutoStartConfirmLib/**'
      - 'AutoStartConfirmSetup/**'
      - 'AutoStartConfirmTests/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'AutoStartConfirm/**'
      - 'AutoStartConfirmLib/**'
      - 'AutoStartConfirmSetup/**'
      - 'AutoStartConfirmTests/**'
      - '.github/workflows/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: 'echo "No build required"'
