name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  
  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Version
        run: echo new version ${{ needs.build.outputs.version_number }}
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download build artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: AutoStartConfirmSetup
          
      - name: Create tag and release
        run: |
          $v = "${{needs.build.outputs.version_number}}" -split "\."
          $semver = ($v | Select-Object -SkipLast 1) -join "."
          gh release create "v${{needs.build.outputs.version_number}}" -d -p --title "$semver" --generate-notes AutoStartConfirmSetup_Standalone.msi AutoStartConfirmSetup_FrameworkDependent.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh        
