name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  
  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: version
        run: echo new version ${{ needs.build.outputs.version_number }}
        
      - name: Download build artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: AutoStartConfirmSetup
          
      - name: Create tag and release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}          
          version: v${{ needs.build.outputs.version_number }}
          assets: '[ "AutoStartConfirmSetup.msi" ]'
          overwrite: false    
  
