name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  
  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Version
        run: echo new version ${{ needs.build.outputs.version_number }}
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download build artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: AutoStartConfirmSetup
          
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Create tag and release
        # todo: change to semver (Major.Minor.Patch)
        run: gh release create v${{needs.build.outputs.version_number}} -d -p --title ${{needs.build.outputs.version_number}} --generate-notes AutoStartConfirmSetup.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
