name: Publish to WinGet
on:
  release:
    types: [released, edited]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: ChristianGalla.AutoStartConfirm
          installers-regex: '^AutoStartConfirmSetup_Standalone\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}
