name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: ChristianGalla.AutoStartConfirm
          installers-regex: '^AutoStartConfirmSetup_Standalone\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}
